### ISSUE TITLE
Iterators seems to be not designed to run on parallel

### ISSUE THREAD

**Issue by 4strodev** [dreamsofcode-io/loop#3]
I think that I found that iterators are not meant to execute yield function concurrently. Doesn't mean that inside your yield function you execute goroutines. But yield function needs to be executed sequentially. See PR #2

**Comment by elliottminns** [comment]
Hey! You are correct. Since version 1.23 the parallel iterator will no longer work and will panic.

Thanks for finding that, I've added a note to the readme!
